// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjpV5Be8QgT6SwTeejqgJntQ0U1Pp4iZU',
    appId: '1:852924809459:web:c6fea069b3a8d4c7673786',
    messagingSenderId: '852924809459',
    projectId: 'malispos',
    authDomain: 'malispos.firebaseapp.com',
    storageBucket: 'malispos.appspot.com',
    measurementId: 'G-GRQFC9XWQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRlzo3qS1BamKoe27vAtSWe_gR6RYm4gw',
    appId: '1:852924809459:android:1a8cece8d02b4057673786',
    messagingSenderId: '852924809459',
    projectId: 'malispos',
    storageBucket: 'malispos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYrbvf8FOeLmOo40K9eaqMZQUWP_ROjE',
    appId: '1:852924809459:ios:4b0bc96224bdfc91673786',
    messagingSenderId: '852924809459',
    projectId: 'malispos',
    storageBucket: 'malispos.appspot.com',
    iosClientId:
        '852924809459-o0uffr3tl6iu45vbe5sj74iducj6f8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.malispos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYrbvf8FOeLmOo40K9eaqMZQUWP_ROjE',
    appId: '1:852924809459:ios:4b0bc96224bdfc91673786',
    messagingSenderId: '852924809459',
    projectId: 'malispos',
    storageBucket: 'malispos.appspot.com',
    iosClientId:
        '852924809459-o0uffr3tl6iu45vbe5sj74iducj6f8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.malispos',
  );
}
